/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rdkoujispkgtetwqiyqe"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJka291amlzcGtndGV0d3FpeXFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0OTE0MjYsImV4cCI6MjA4NTA2NzQyNn0.bkQgrmjZg1Pc-cW_Nr9ktQcDtQs4sFKTRbfbPhoNwkE"
